### ISSUE TITLE
application icon broken in ubuntu 18.04 alpha dash area

### ISSUE THREAD

**Issue by MichinariNukazawa** [unindented/electron-installer-debian#135] opened 2018-03-14 15:24 UTC
**What version of `electron-installer-debian` are you using?**
0.8.1

**What version of `node` and `npm` are you using?**
v6.12.0/3.5.2

**What operating system are you using?**
Ubuntu 18.04 alpha

**Can you compile the [example app](https://github.com/unindented/electron-installer-debian/tree/master/example) successfully?**
yes

**What did you do? Please include the configuration you are using for `electron-installer-debian`.**
```
{
	"name": "daisy-sequence",
	"src": "../release/release/daisy_sequence-linux-x64/",
	"dest": "../release/release/",
	"arch": "amd64",
	"icon": "image/icon.png",
	"categories": [
		"Utility"
	],
	"lintianOverrides": [
		"changelog-file-missing-in-native-package"
	]
}
```

**What did you expect to happen?**
The application icon is displayed correctly in the Dash area on the left side of the screen

**What actually happened?**
Application icon is not displayed correctly

** Other **
In Ubuntu 16.04 the application icon was displayed correctly.
In Ubuntu 18.04 application search (Alt + F2), icons are displayed correctly.
(To be honest, I think that this problem is a problem that Ubuntu changed its specifications)

screenshot  
![screenshot](https://user-images.githubusercontent.com/3787401/37411673-b4bcb090-27e6-11e8-942b-3b0f1b648363.png)

icon file  
![icon](https://user-images.githubusercontent.com/3787401/37411776-ec831e60-27e6-11e8-8e8b-e6b7c5f1a564.png)

**Comment by fcastilloec** [comment] 2018-03-14 17:08
Given that Ubuntu 18.04 is still under development, we really don't know what's going on.
This is **very** likely an Ubuntu bug rather than a bug on our side. We'll have to keep an eye on this. I'll appreciate it if you can keep testing with future releases and keeps us updated

**Comment by MichinariNukazawa** [comment] 2018-03-15 13:40
If this problem is a Ubuntu bug, we should report a bug before it is released.
Although I can report it, I am not an English speaker, so I'm not sure I can communicate correctly.

**Comment by MichinariNukazawa** [comment] 2018-03-19 13:28
Because I can not make it in time for release unless I keep doing anything like this, will I write a bug report for Ubuntu launchpad?

**Comment by malept** [comment] 2018-03-19 16:47
You should see if the bug exists in Ubuntu 17.10 as well. If not, file a bug at Ubuntu's issue tracker.

**Comment by fcastilloec** [comment] 2018-05-12 21:06
I've been using Ubuntu 18.04 for 2 weeks now and I can't reproduce this in any way. I'm going to close this issue. @MichinariNukazawa if you still have problems , feel free to re-open the issue with more details, and maybe a log output

**Closed by fcastilloec** 2018-05-12 21:06 UTC

**Comment by MichinariNukazawa** [comment] 2018-05-13 01:40
I reploduction now, in Ubuntu 18.04 release (clean installed release version).

Install log output:
`sudo dpkg -i --debug=20 --log=log20.log lina-dicto-english_0.1.14_amd64.deb`
[log20.log](https://github.com/unindented/electron-installer-debian/files/1998044/log20.log)

**Comment by fcastilloec** [comment] 2018-05-13 04:43
I took a quick look at your repository and the problem is not with this package, it's that you never assigned an icon to the window you create in electron.
If you change [`index.js#L14`](https://github.com/MichinariNukazawa/lina_dicto/blob/master/lina_dicto/index.js#L14) to look like the following:

```js
win = new BrowserWindow({
  width: 800,
  height: 600,
  icon: 'image/icon.png'
})
```

And just do `npm run build` you will already see that your program has an icon when running on Ubuntu 18.04. With the old code, if you just did `npm run build` or `electron .` your app never had an icon, so even when packaging it, you still don't have an icon.

**Comment by MichinariNukazawa** [comment] 2018-05-13 05:37
I solved my application problem.
Thank you.
