### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by daaru00** [unindented/electron-installer-debian#54] opened 2017-02-16 13:25 UTC
Which dependencies are strictly required in **options.depends** if you do not use any external library? 
Default value is:
```
git, gconf2, gconf-service, gvfs-bin, libc6, libcap2, libgtk2.0-0, libudev0 | libudev1, libgcrypt11 | libgcrypt20, libnotify4, libnss3, libxtst6, python, xdg-utils
``` 
why `git` and `python`?

**Comment by unindented** [comment] 2017-02-16 22:55
Duplicate of https://github.com/unindented/electron-installer-debian/issues/52

**Closed by unindented** 2017-02-16 22:55 UTC
